name: toml_viewer
version: 0.0.2
description: A  flutter library embeded TOML view.
repository: https://github.com/sudhi001/toml_viewer
homepage: https://github.com/sudhi001/toml_viewer
issue_tracker: https://github.com/sudhi001/toml_viewer/issues
screenshots:
  - description: 'Logo of formstack framework'
    path: screens/screen1.png

topics: [toml, viewer]


environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  toml: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

